/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  RewardDistribution,
  RewardDistributionInterface,
} from "../RewardDistribution";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "newReward",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newRewardStartId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "oldReward",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "oldRewardDistributed",
        type: "uint256",
      },
    ],
    name: "NewReward",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "reward",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "RewardDistributed",
    type: "event",
  },
] as const;

export class RewardDistribution__factory {
  static readonly abi = _abi;
  static createInterface(): RewardDistributionInterface {
    return new Interface(_abi) as RewardDistributionInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): RewardDistribution {
    return new Contract(address, _abi, runner) as unknown as RewardDistribution;
  }
}
