/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { Rewardable, RewardableInterface } from "../Rewardable";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class Rewardable__factory {
  static readonly abi = _abi;
  static createInterface(): RewardableInterface {
    return new Interface(_abi) as RewardableInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Rewardable {
    return new Contract(address, _abi, runner) as unknown as Rewardable;
  }
}
