/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IReward, IRewardInterface } from "../IReward";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "rewardId",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IReward__factory {
  static readonly abi = _abi;
  static createInterface(): IRewardInterface {
    return new utils.Interface(_abi) as IRewardInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IReward {
    return new Contract(address, _abi, signerOrProvider) as IReward;
  }
}
